version: '3.8'
services:
  virus-simulation:
    build:
      context: .
      args:
        - MAPBOX_TOKEN=${MAPBOX_TOKEN}
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - MAPBOX_TOKEN=${MAPBOX_TOKEN}
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3 